version: '3'
services:
  flox:
    build: '.'
    image: flox:latest
    restart: unless-stopped
    ports: ["8888:80"]
    networks:
      - internal
    depends_on:
      - mysql
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
      - APACHE_RUN_USER_ID=33
      - APACHE_RUN_GROUP_ID=33
      - FLOX_DB_NAME=flox # same as {MYSQL_DATABASE} from below
      - FLOX_DB_USER=flox_user # same as {MYSQL_USER} from below
      - FLOX_DB_PASS=flox_pass # same as {MYSQL_PASSWORD} from below
      - FLOX_DB_HOST=mysql 
      - FLOX_DB_PORT=3306 # same as {mysql::ports} from below
      - TMDB_API_KEY=fce675de8abd8761b876b98554ac3254339
      - FLOX_ADMIN_USER=admin
      - FLOX_ADMIN_PASS=admin # Remember to change your password

  # MySQL image with a default database cells and a dedicated user pydio
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    ports: ["3306:3306"]
    networks:
      - internal
    environment:
      MYSQL_ROOT_PASSWORD: password # Remember to change your password

      MYSQL_DATABASE: flox
      MYSQL_USER: flox_user
      MYSQL_PASSWORD: flox_pass # Remember to change your password  
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:

networks:
  internal:
